<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>QuickSType.Core.Tests</RootNamespace>
    <AssemblyName>QuickSType.Core.Tests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.0.1" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\QuickSType.Core\QuickSType.Core.csproj" />
    <ProjectReference Include="..\..\src\QuickSType.Platform.Mac\QuickSType.Platform.Mac.csproj" Condition="$([MSBuild]::IsOSPlatform('OSX'))" />
  </ItemGroup>

</Project>
