<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>QuickSType.Core</RootNamespace>
    <AssemblyName>QuickSType.Core</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ManySpeech.SileroVad" Version="1.1.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    <PackageReference Include="SharpHook" Version="7.1.1" />
    <PackageReference Include="Whisper.net" Version="1.9.0" />
    <PackageReference Include="PortAudioSharp2" Version="1.0.6" />
    <PackageReference Include="TextCopy" Version="6.2.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="QuickSType.Core.Tests" />
  </ItemGroup>

</Project>
