<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>QuickSType.Platform.Windows</RootNamespace>
    <AssemblyName>QuickSType.Platform.Windows</AssemblyName>
    <IsAotCompatible>true</IsAotCompatible>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuickSType.Core\QuickSType.Core.csproj" />
  </ItemGroup>

</Project>
